---
pack: data/char_180_amgoat_1_front.zip
actions:
  - trigger: Space
    sequence:
      - name: Attack
  - trigger: X
    sequence:
      - name: Skill_Begin
      - name: Skill_Loop
        loop: true
        length: 5.0
      - name: Skill_End
  - trigger: Z
    sequence:
      - name: Die
    return_to_idle: false
idle_animation: Idle
window_size:
  - 348.8
  - 459.2
window_position:
  - 700.0
  - 258.4
scale: 1.1
